// user.go provides a facility for proxying user-generated bytestreams - ie, streams which
// originate from a process running on the user's computer (like a web browser) or streams which
// are generated as part of the user's Lantern control plane activity. We can operationalize a
// user stream in a WorkerFSM just like we do an RTCPeerConnection or a websocket.Conn, such that
// bytestreams from the user can be neatly managed alongside bytestreams from remote peers in
// their consumer table. In other words: we treat the user's web browser just like any connected consumer.
package clientcore

import (
	"context"
	"encoding/json"
	"net"
	"os"
	"sync"
	"sync/atomic"
	"time"

	"github.com/google/uuid"

	"github.com/getlantern/broflake/common"
)

// Data-plane stats instrumentation. Gated behind the BROFLAKE_STATS env
// var so production builds pay zero cost (no atomic increments, no
// background goroutine, no log volume) while debug runs get per-second
// summaries of the four data-plane choke points.
//
// Set BROFLAKE_STATS=1 before launch (or in a systemd unit for a widget)
// to enable.
//
// bfStatsEnabled is evaluated once at init so we don't re-stat the env
// on the hot Read/Write path.
var bfStatsEnabled = os.Getenv("BROFLAKE_STATS") != ""

// bfConnStats tracks per-direction cumulative bytes on the consumer-side
// BroflakeConn so we can confirm whether QUIC handshake traffic is
// actually reaching bfconn.Read (and whether our Writes are being
// dropped because the outgoing IPC channel is full). Updated by every
// ReadFrom / WriteTo call; read by a single goroutine that logs a
// compact summary once a second. Using atomics keeps the hot path
// lock-free.
//
// These are intentionally process-global rather than per-BroflakeConn:
// broflake runs exactly one BroflakeConn per process (one Broflake engine
// per Lantern tunnel), so global aggregation matches reality. If that
// ever changes, the log line would become ambiguous and we'd need to
// key by LocalAddr().
var (
	bfReadBytes       atomic.Uint64
	bfReadCalls       atomic.Uint64
	bfWriteBytes      atomic.Uint64
	bfWriteCalls      atomic.Uint64
	bfWriteDropCalls  atomic.Uint64
	bfStatsLoggerOnce sync.Once
)

func startBfConnStatsLoggerOnce() {
	if !bfStatsEnabled {
		return
	}
	bfStatsLoggerOnce.Do(func() {
		go func() {
			t := time.NewTicker(time.Second)
			defer t.Stop()
			var lastR, lastRC, lastW, lastWC, lastWD uint64
			for range t.C {
				r, rc := bfReadBytes.Load(), bfReadCalls.Load()
				w, wc := bfWriteBytes.Load(), bfWriteCalls.Load()
				wd := bfWriteDropCalls.Load()
				dR, dRC := r-lastR, rc-lastRC
				dW, dWC := w-lastW, wc-lastWC
				dWD := wd - lastWD
				lastR, lastRC, lastW, lastWC, lastWD = r, rc, w, wc, wd
				// Only log when *something* happened this second; a
				// perfectly quiet tunnel would otherwise add one line
				// per second of noise forever.
				if dR+dW+dWD > 0 {
					common.Debugf(
						"bfconn 1s summary: read %d bytes in %d calls, "+
							"wrote %d bytes in %d calls, %d writes dropped "+
							"(channel full)",
						dR, dRC, dW, dWC, dWD,
					)
				}
			}
		}()
	})
}

type BroflakeConn struct {
	writeChan          chan IPCMsg
	readChan           chan IPCMsg
	addr               common.DebugAddr
	readDeadline       time.Time
	updateReadDeadline chan time.Time
}

func (c BroflakeConn) LocalAddr() net.Addr {
	return c.addr
}

func (c BroflakeConn) ReadFrom(p []byte) (n int, addr net.Addr, err error) {
	if bfStatsEnabled {
		startBfConnStatsLoggerOnce()
	}
	for {
		var ctx context.Context

		// If the deadline is zero value, never expire; otherwise obey the deadline
		if c.readDeadline.IsZero() {
			ctx, _ = context.WithCancel(context.Background())
		} else {
			ctx, _ = context.WithDeadline(context.Background(), c.readDeadline)
		}

		select {
		case msg := <-c.readChan:
			// The read completed, let's return some bytes!
			payload := msg.Data.([]byte)

			var unboundedPacket common.UnboundedPacket

			err := json.Unmarshal(payload, &unboundedPacket)
			if err != nil {
				// XXX: it's unclear what the desired behavior is here. Before the introduction of
				// UnboundedPacket, there was no precedent for returning an error after successfully reading
				// from the channel. Returning an error here may break things catastrophically, but if
				// we couldn't unmarshal the packet, we do have a catastrophic situation on our hands...
				return 0, nil, err
			}

			// copy returns the actual number of bytes written to p,
			// which may be less than len(Payload) if the caller's
			// buffer is short. Return that value — returning
			// len(Payload) would violate the net.PacketConn contract
			// (n <= len(p)) and also over-count bfReadBytes.
			n := copy(p, unboundedPacket.Payload)
			if bfStatsEnabled {
				bfReadBytes.Add(uint64(n))
				bfReadCalls.Add(1)
			}
			return n, common.DebugAddr(unboundedPacket.SourceAddr), nil
		case <-ctx.Done():
			// We're past our deadline, so let's return failure!
			return 0, nil, ctx.Err()
		case d := <-c.updateReadDeadline:
			// Someone updated the read deadline, so let's iterate to respect the new deadline
			c.readDeadline = d
		}
	}
}

func (c BroflakeConn) WriteTo(p []byte, addr net.Addr) (n int, err error) {
	if bfStatsEnabled {
		startBfConnStatsLoggerOnce()
	}
	// TODO: This copy seems necessary to avoid a data race
	b := make([]byte, len(p))
	copy(b, p)

	select {
	case c.writeChan <- IPCMsg{IpcType: ChunkIPC, Data: b}:
		// Do nothing, message sent
		if bfStatsEnabled {
			bfWriteBytes.Add(uint64(len(b)))
			bfWriteCalls.Add(1)
		}
	default:
		// Drop the chunk if we can't keep up with the data rate.
		// Tracked so we can tell a QUIC handshake stall from a
		// back-pressure drop in the bfconn stats summary.
		if bfStatsEnabled {
			bfWriteDropCalls.Add(1)
		}
	}

	return len(b), nil
}

func (c BroflakeConn) Close() error {
	return nil
}

// XXX: A note about deadlines: as of quic-go 0.34, the QUIC dialer didn't seem to care about read
// or write deadlines, and it was happy to use a net.PacketConn which didn't properly implement them.
// But when we bumped to quic-go 0.40, it emerged that the dialer wouldn't work unless we added
// support for read deadlines. Since there's still no evidence that the dialer cares about write
// deadlines, we haven't added support for those yet.
func (c BroflakeConn) SetReadDeadline(t time.Time) error {
	c.updateReadDeadline <- t
	return nil
}

func (c BroflakeConn) SetWriteDeadline(t time.Time) error {
	return nil
}

func (c BroflakeConn) SetDeadline(t time.Time) error {
	return nil
}
func NewProducerUserStream(wg *sync.WaitGroup) (*BroflakeConn, *WorkerFSM) {
	worker := NewWorkerFSM(wg, []FSMstate{
		FSMstate(func(ctx context.Context, com *ipcChan, input []interface{}) (int, []interface{}) {
			// State 0
			// (no input data)
			common.Debugf("User stream producer state 0...")
			// TODO: check for a non-nil path assertion to alert the UI that we're ready to proxy?
			select {}
		}),
	})

	bfconn := BroflakeConn{
		writeChan:          worker.com.tx,
		readChan:           worker.com.rx,
		addr:               common.DebugAddr(uuid.NewString()),
		readDeadline:       time.Time{},
		updateReadDeadline: make(chan time.Time, 512),
	}

	return &bfconn, worker
}
